### PR TITLE
[#500] Fix PUT endpoint for Institutions

### LINKED ISSUE #500: Some of the fields of an institution doesn't update on PUT
**Steps to reproduce**

Send PUT to `http://localhost:4200/api/v1/institutions/zarzadzenie-kryzysowe-pl` with body

{"slug":"zarzadzenie-kryzysowe-pl","name":"Zarządzenie kryzysowe - PL","address":"dawdad","postalCode":"32-465","city":"wwww","phone":"000000000","emblem":"iVBORw0KGgoAAAANSUhEUgAAAEYA...","secondaryPhone":null,"institutionAdminEmail":null}

**Expected result**
GET for `http://localhost:4200/api/v1/institutions/zarzadzenie-kryzysowe-pl` should return

{"slug":"zarzadzenie-kryzysowe-pl","name":"Zarządzenie kryzysowe - PL","address":"dawdad","postalCode":"32-465","city":"wwww","phone":"000000000","emblem":"static/emblems/zarzadzenie-kryzysowe-pl","secondaryPhone":null,"institutionAdminEmail":null}

**What happened instead?**
GET for `http://localhost:4200/api/v1/institutions/zarzadzenie-kryzysowe-pl` return

{"name":"Zarządzenie kryzysowe - PL","address":null,"city":null,"postalCode":null,"phone":null,"secondaryPhone":null,"emblem":"static/emblems/zarzadzenie-kryzysowe-pl","parentName":null,"slug":"zarzadzenie-kryzysowe-pl","parentSlug":null}

### PR DESCRIPTION
**Pull request by kmarszalek**
Closes #500.

### CODE REVIEW

File: s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java [hunk 1]
```diff
@@ -139,8 +139,14 @@ public void update(UpdateInstitutionRequest request, String institutionSlug)
...
         uploadEmblemIfRequested(slug, request.getEmblem());
+
         institution.setName(request.getName());
         institution.setSlug(slug);
+        institution.setAddress(request.getAddress());
+        institution.setCity(request.getCity());
+        institution.setPostalCode(request.getPostalCode());
+        institution.setPhone(request.getPhone());
+        institution.setSecondaryPhone(request.getSecondaryPhone());
         update(institution);
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java:150]: I don't think this is necessary, this call should be removed alongside the method calling save.
You\re within a transaction here, so any changes will be saved automatically when leaving it.
