### PR TITLE
[#551] Super admin security issues

### LINKED ISSUE #551: Fix super admin settings menu
When logged in as admin@admin.pl (super admin), the user cannot choose an institution and therefore cannot edit groups, persons, or institutions.
Steps to reproduce:
1. Login as admin@admin.pl
2. go to settings/dashboard
3. Try to edit settings/people, or settings/institutions.

These settings are working as expected when logged in as ZkAdmin User.

### PR DESCRIPTION
**Pull request by kmarszalek**
fix condition on getAll for admin endpoint
fix security rule for access to /institutions/{institution} to let through super admin

Closes #551

### CODE REVIEW

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 1]
```diff
@@ -29,6 +29,7 @@
 @AutoConfigureMockMvc
 public class InstitutionControllerTest {
     public static final String PROFILE_EMAIL = "get@profile.com";
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:31]: remove this line

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 2]
```diff
@@ -29,6 +29,7 @@
...
+    public static final String ADMIN_EMAIL = "admin@profile.com";
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:32]: remove this line

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 3]
```diff
@@ -29,6 +29,7 @@
 @AutoConfigureMockMvc
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:29]: In previous PR I've created generic use helper (factory) to generate unique element mock to create
- institution
- group
- user
- invitation

it's called `InvitationHelper`. It would be nice if you replace all mocks in this test and recall class with a more generic name like `Factory`.

Even if it isn't ticket scope for such changes
- code will be simpler
- there will be fewer lines of code (around 50 - 70)
- it will be a good moment to propagate factory methodology from now on
- you will be not worried about fields and names any longer
- if there will be a change in a model (DB), mock will be changed in one place (factory)

(optional)
You can generate all necessary mocks in before function

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 4]
```diff
@@ -70,6 +72,15 @@ public void beforeEach() {
                 .enabled(true)
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:72]: replace with user mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 5]
```diff
@@ -70,6 +72,15 @@ public void beforeEach() {
...
                 .build());
 
+        admin = appUserRepository.save(AppUser.builder()
+                .email(ADMIN_EMAIL)
+                .name("Get")
+                .surname("Profile")
+                .password("{noop}password")
+                .enabled(true)
+                .admin(true)
+                .build());
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:82]: - add adminBuilder method to `Factory` class
- replace this mock with it

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 6]
```diff
@@ -70,6 +72,15 @@ public void beforeEach() {
...
+
         slugInstitution = slugService.slugify(testInstitution);
         Institution institution = institutionRepository.save(Institution.builder()
                 .name(testInstitution)
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:86]: - replace institution mock
- replace group mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 7]
```diff
@@ -114,7 +125,7 @@ public void shouldGetEmptySet() throws Exception {
     }
 
     @Test
-    public void shouldGetAllUsersInstitutions() throws Exception {
+    public void shouldGetAllInstitutionsForUser() throws Exception {
         String testInstitutionZK = "Test Institution ZK";
         String slugInstitutionZK = slugService.slugify(testInstitutionZK);
         Institution institution = institutionRepository.save(Institution.builder()
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:131]: - replace institution mock x2
- replace group mock x2

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 8]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
     }
 
     @Test
-    public void shouldReturnUnauthorized() throws Exception {
+    public void shouldGetAllInstitutionsForAdmin() throws Exception {
+        String testInstitutionZK = "Test Institution ZK";
+        String slugInstitutionZK = slugService.slugify(testInstitutionZK);
+        Institution institution = institutionRepository.save(Institution.builder()
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:171]: replace with institution mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 9]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .name(testInstitutionZK)
+                .slug(slugInstitutionZK)
+                .build());
+        Group group = groupRepository.save(Group.builder().name("__default__").slug("default").institution(institution).build());
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:175]: replace with group mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 10]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+
+        String testInstitutionZK_MAZ = "Test Institution ZK - Mazowieckie";
+        String slugInstitutionZK_MAZ = slugService.slugify(testInstitutionZK_MAZ);
+        Institution institution2 = institutionRepository.save(Institution.builder()
+                .name(testInstitutionZK_MAZ)
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:180]: replace with institution mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 11]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .slug(slugInstitutionZK_MAZ)
+                .parent(institution)
+                .build());
+        Group group2 = groupRepository.save(Group.builder().name("__default__").slug("default").institution(institution2).build());
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:184]: replace with group mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 12]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+
+        String testInstitutionPAK = "Test Institution PAK";
+        String slugInstitutionPAK = slugService.slugify(testInstitutionPAK);
+        institution = institutionRepository.save(Institution.builder()
+                .name(testInstitutionPAK)
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:189]: replace with institution mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 13]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .slug(slugInstitutionPAK)
+                .build());
+        groupRepository.save(Group.builder().name("__default__").slug("default").institution(institution).build());
+
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:193]: replace with group mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 14]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .andExpect(status().isOk())
+                .andExpect(jsonPath("$.length()", is(equalTo(4))));
+    }
+
+    @Test
+    public void shouldGetInstitutionForAdmin() throws Exception {
+        String testInstitutionZK = "Test Institution ZK";
+        String slugInstitutionZK = slugService.slugify(testInstitutionZK);
+        Institution institution = institutionRepository.save(Institution.builder()
+                .name(testInstitutionZK)
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:206]: replace with institution mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 15]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .slug(slugInstitutionZK)
+                .build());
+        Group group = groupRepository.save(Group.builder().name("__default__").slug("default").institution(institution).build());
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:209]: replace with group mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 16]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .andExpect(jsonPath("$.length()", is(equalTo(10))))
+                .andExpect(jsonPath("$.slug", is(equalTo(slugInstitutionZK))));
+    }
+
+    @Test
+    public void shouldGetInstitutionForMember() throws Exception {
+        String testInstitutionZK = "Test Institution ZK";
+        String slugInstitutionZK = slugService.slugify(testInstitutionZK);
+        Institution institution = institutionRepository.save(Institution.builder()
+                .name(testInstitutionZK)
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:224]: replace with institution mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 17]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .slug(slugInstitutionZK)
+                .build());
+        Group group = groupRepository.save(Group.builder().name("__default__").slug("default").institution(institution).build());
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:227]: replace with group mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 18]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .andExpect(status().isOk())
+                .andExpect(jsonPath("$.length()", is(equalTo(10))))
+                .andExpect(jsonPath("$.slug", is(equalTo(slugInstitutionZK))));
+    }
+
+    @Test
+    public void shouldReturnUnauthorizedForInstitution() throws Exception {
+        String testInstitutionZK = "Test Institution ZK";
+        String slugInstitutionZK = slugService.slugify(testInstitutionZK);
+        Institution institution = institutionRepository.save(Institution.builder()
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:241]: replace with institution mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 19]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .name(testInstitutionZK)
+                .slug(slugInstitutionZK)
+                .build());
+        Group group = groupRepository.save(Group.builder().name("__default__").slug("default").institution(institution).build());
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:245]: replace with group mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 20]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
         mockMvc.perform(get(API_PREFIX_V1 + "/institutions")
                 .contentType(MediaType.APPLICATION_JSON))
                 .andExpect(status().isUnauthorized());
     }
+
+    @Test
+    public void shouldReturnForbiddenForInstitution() throws Exception {
+        String testInstitutionZK = "Test Institution ZK";
+        String slugInstitutionZK = slugService.slugify(testInstitutionZK);
+        Institution institution = institutionRepository.save(Institution.builder()
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:263]: replace with institution mock

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java [hunk 21]
```diff
@@ -154,9 +165,109 @@ public void shouldGetAllUsersInstitutions() throws Exception {
...
+                .name(testInstitutionZK)
+                .slug(slugInstitutionZK)
+                .build());
+        Group group = groupRepository.save(Group.builder().name("__default__").slug("default").institution(institution).build());
```
Comment (danielkryska) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java:267]: replace with group mock

**Comment by kmarszalek** [comment]
@danielkryska comments solved via #637

File: CHANGELOG.md [hunk 22]
```diff
@@ -30,6 +30,7 @@ The most recent changes are on top, in each type of changes category.
 
 ### Fixed
 
+- Super admin security issues [#551](https://github.com/cyfronet-fid/sat4envi/issues/551)
```
Comment (jswk) [inline CHANGELOG.md:33]: Move to unreleased
