### PR TITLE
[#838] Fix date handling in search API

### LINKED ISSUE #838: time related problem in search API
ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
    at pl.cyfronet.s4e.api.SearchConverter.setTime(SearchConverter.java:94)
    at pl.cyfronet.s4e.api.SearchConverter.convert(SearchConverter.java:30)
    at pl.cyfronet.s4e.service.SearchService.parseToParamMap(SearchService.java:28)
    at pl.cyfronet.s4e.api.OSearchController.getScenesDHusStyle(OSearchController.java:53)
    at jdk.internal.reflect.GeneratedMethodAccessor544.invoke
...
(78 additional frame(s) were not displayed)

### PR DESCRIPTION
**Pull request by kmarszalek**
- add brackets handling in params for tomcat

Closes #838

### CODE REVIEW

File: s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java [hunk 1]
```diff
@@ -90,6 +91,8 @@ private void setTime(Map<String, String> queryParamMap, Map<String, Object> resu
                     .replaceAll("\\s+", "")
                     .split("TO");
             String[] ingestionParams = getQueryParam(paramName).split(":");
+            if (times.length < 2 || ingestionParams.length < 2)
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java:94]: I'd test both for equality. More than 2 also indicates something is not yes.

**Review by jswk — APPROVED** [review]

**Review by wziajka — APPROVED** [review]
