### PR TITLE
[#1168][#1149] Fix quicklook image visibility, fix not loading scene on first product selection

### LINKED ISSUE #1168: Fit sentinel search quicklook image for searched item
Reference: https://jira.cyfronet.pl/jira/projects/SWT/issues/SWT-5?filter=allopenissues (close after merge)

Steps to reproduce
1. go to /map/sentinel-search
2. check sentinel-2
3. search

What happens?
Most of results has black quicklook images, due to real size display in cutted window.

What should happened?
Quicklook image should fit to item image boundaries.

### PR DESCRIPTION
**Pull request by danielkryska**
- QuickLook image background at /map/sentinel-search (after search) is centered
and cover whole div (fix the issue when Quicklook is mostly black icon)
- now on the first product selection loaded scene will be displayed

Closes #1168, #1149

### CODE REVIEW

**Review by jswk — CHANGES_REQUESTED** [review]
Please correct the lint errors so that PR and tests work.

**Review by michal-szostak — APPROVED** [review]

File: s4e-web/src/app/views/map-view/map-view.component.ts [hunk 1]
```diff
@@ -222,6 +222,12 @@ export class MapViewComponent implements OnInit, OnDestroy {
     if (this.mapQuery.isLoading()) {
       return;
     }
+
+    // IMPORTANT!!! Prevent loading random date (1970-01-01) on first product visit
```
Comment (jswk) [inline s4e-web/src/app/views/map-view/map-view.component.ts:226]: It's not really random, it's arbitrary: https://en.wikipedia.org/wiki/Unix_time.

**Review by jswk — APPROVED** [review]

File: s4e-web/src/app/views/map-view/map-view.component.ts (hunk 1 above)
Comment (danielkryska) [reply s4e-web/src/app/views/map-view/map-view.component.ts:226]: You're right in the case of Unix time, but the comment is related to randomly showing the `NaN` value date. Maybe I wasn't too precised.
