### PR TITLE
[#1140] Fix license handling in search endpoints

### LINKED ISSUE #1140: [Fix] handling 403 error for downloading scene with Eumetsat license (MSG_Raw)
Tested on instance SOK version
SOK version v17.2.1

**Steps:**
1. Log in
2. Go to "Szukaj Danych"
3. Select MSG Raw v1 (set sorting by sensing time) and click the button "Szukaj" - list of available data is displayed
4. Click the download button obraz

**What happens?**
obraz

**What was expected to happen?**
User see information about lack of license

### PR DESCRIPTION
**Pull request by kmarszalek**
28 records, 2 with eumetsat license, one with a full hour.
Search for Eumetsat license product for anonymous:
Zrzut ekranu 2021-03-10 o 16 01 39

Search for Eumetsat license product for zkMember
Zrzut ekranu 2021-03-10 o 16 06 32

Closes #1140

### CODE REVIEW

File: s4e-backend/src/main/java/pl/cyfronet/s4e/config/QueryConfig.java [hunk 1]
```diff
@@ -23,15 +23,18 @@
 import org.springframework.context.annotation.Configuration;
 import pl.cyfronet.s4e.data.repository.query.*;
 
+import java.time.Duration;
 import java.util.List;
 import java.util.function.Function;
 
 @Configuration
 public class QueryConfig {
     final SpringDataWebProperties springDataWebProperties;
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/config/QueryConfig.java:32]: I missed the private keyword here, I'd add it in this line too.

File: s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java [hunk 2]
```diff
@@ -59,6 +65,23 @@ private void queryBySensingTime(Map<String, Object> params,
         }
     }
 
+    private void applyLicense(Map<String, Object> params,
+                              List<Object> parameters,
+                              StringBuilder resultQuery) {
+        if (params.containsKey(ACCESS_TYPE) && params.get(ACCESS_TYPE).equals(Product.AccessType.EUMETSAT)) {
+            LocalDateTime now = LocalDateTime.now();
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java:72]: Don't access timestamp like this, it will make writing tests difficult, rather use Clock instance, as in EumetsatLicense among others

File: s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java [hunk 3]
```diff
@@ -59,6 +65,23 @@ private void queryBySensingTime(Map<String, Object> params,
...
+            resultQuery.append(" AND ( ").append(getMetadataTime("sensing_time")).append(" <= ?");
+            ZonedDateTime limit = now.atZone(ZoneId.of("UTC")).minus(freshDuration);
+            parameters.add(limit);
+            resultQuery.append(" OR  ").append(getMetadataTime("sensing_time")).append(" IN (?) )");
+            parameters.add(Arrays.asList(
+                    now.withMinute(0).withSecond(0).withNano(0),
+                    now.withMinute(0).withSecond(0).withNano(0).minusHours(1),
+                    now.withMinute(0).withSecond(0).withNano(0).minusHours(2)
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java:80]: Calculate these dynamically based on the freshDuration

File: s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java [hunk 4]
```diff
@@ -59,6 +65,23 @@ private void queryBySensingTime(Map<String, Object> params,
         }
     }
 
+    private void applyLicense(Map<String, Object> params,
+                              List<Object> parameters,
+                              StringBuilder resultQuery) {
+        if (params.containsKey(ACCESS_TYPE) && params.get(ACCESS_TYPE).equals(Product.AccessType.EUMETSAT)) {
+            LocalDateTime now = LocalDateTime.now();
+            resultQuery.append(" AND ( ").append(getMetadataTime("sensing_time")).append(" <= ?");
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java:73]: I'd remove the superfluous space after the opening paren, i.e. `" AND ( "` => `" AND ("`.
Same for below: `" OR  "` => `" OR "`, `" IN (?) )"` => `" IN (?))"`.

File: s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java [hunk 5]
```diff
@@ -43,6 +58,32 @@ public Long getCountBy(Map<String, Object> params) throws SQLException, QueryExc
...
+        }
+    }
+
+    public void applyLicenseByProductType(Map<String, Object> params) throws NotFoundException {
+        val product =
+                productRepository.findByName(
+                        String.valueOf(params.get(PRODUCT_TYPE)), Product.class)
+                        .orElseThrow(() -> new NotFoundException("Product not found"));
+        val accessType = product.getAccessType();
+        AppUserDetails userDetails = AppUserDetailsSupplier.get();
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java:73]: Rather extract the AppUserDetails in controller and pass it to the method as parameter, the way it's done in most other places

File: s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java [hunk 6]
```diff
@@ -43,6 +58,32 @@ public Long getCountBy(Map<String, Object> params) throws SQLException, QueryExc
...
+        if (Product.AccessType.EUMETSAT.equals(accessType)) {
+            // if user doesnt have proper license add parameter to get older scenes
+            if (!userDetails.getAuthorities().contains(new SimpleGrantedAuthority("LICENSE_EUMETSAT"))) {
+                params.put(SearchQueryParams.ACCESS_TYPE, Product.AccessType.EUMETSAT);
+            }
+        } else if (Product.AccessType.PRIVATE.equals(accessType)) {
+            // if user doesnt have proper license throw 403
+            if (!licensePermissionEvaluator.allowProductRead(product.getId(), userDetails)) {
+                throw new AccessDeniedException("Access Denied");
+            }
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java:83]: Do this check regardless of the license type, before even checking for the EUMETSAT type

File: s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java [hunk 7]
```diff
@@ -43,6 +58,32 @@ public Long getCountBy(Map<String, Object> params) throws SQLException, QueryExc
...
+    public void applyLicenseByProductType(Map<String, Object> params) throws NotFoundException {
+        val product =
+                productRepository.findByName(
+                        String.valueOf(params.get(PRODUCT_TYPE)), Product.class)
+                        .orElseThrow(() -> new NotFoundException("Product not found"));
+        val accessType = product.getAccessType();
+        AppUserDetails userDetails = AppUserDetailsSupplier.get();
+        if (Product.AccessType.EUMETSAT.equals(accessType)) {
+            // if user doesnt have proper license add parameter to get older scenes
+            if (!userDetails.getAuthorities().contains(new SimpleGrantedAuthority("LICENSE_EUMETSAT"))) {
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java:76]: Make sure to add a null check here, so that you don't get NPE for an unauthenticated user. See EumetsatLicense::hasLicense.

File: s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java [hunk 8]
```diff
@@ -43,6 +58,32 @@ public Long getCountBy(Map<String, Object> params) throws SQLException, QueryExc
         return repository.countAllByParamsMap(params);
     }
 
+    public void checkProductTypePresent(Map<String, Object> params) throws BadRequestException {
+        if (params.get(PRODUCT_TYPE) == null) {
+            throw new BadRequestException("No product type.");
+        }
+    }
+
+    public void applyLicenseByProductType(Map<String, Object> params) throws NotFoundException {
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java:67]: Upon entry to this method I would strip any existing accessType key present in params, just to be safe it's value wasn't injected.

File: s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java [hunk 9]
```diff
@@ -88,10 +93,13 @@
     public Long getCountDHusStyle(
             @RequestParam(value = "q", required = false) String query,
             @RequestParam(defaultValue = "UTC") ZoneParameter timeZone
-    ) throws BadRequestException, SQLException, QueryException {
+    ) throws BadRequestException, SQLException, QueryException, NotFoundException {
         // TODO: format
         try {
-            return searchService.getCountBy(searchService.countParseToParamMap(query));
+            val params =  searchService.countParseToParamMap(query);
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java:99]: Remove double space.

File: s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java [hunk 10]
```diff
@@ -65,10 +67,13 @@
             @RequestParam(value = "format", defaultValue = "") String format,//json/xml?
             @RequestParam(value = "orderby", required = false) String orderby,//beginposition/ingestiondate asc/desc q=?
             @RequestParam(defaultValue = "UTC") ZoneParameter timeZone
-    ) throws BadRequestException, SQLException, QueryException {
+    ) throws BadRequestException, SQLException, QueryException, NotFoundException {
         // TODO: format
         try {
-            return searchService.getScenesBy(searchService.parseToParamMap(rowsSize, rowStart, orderby, query)).stream()
+            val params =  searchService.parseToParamMap(rowsSize, rowStart, orderby, query);
```
Comment (jswk) [inline s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java:73]: Remove double space.

**Review by jswk — COMMENTED** [review]
Make sure to mark the productType param as required in API description (both in howto and SearchQueryParams.QueryParameters).

**Review by jswk — APPROVED** [review]

**Review by michal-szostak — APPROVED** [review]
Code is OK - I would wait for @Marcelinna to check whether the end issue has been removed.
