### PR TITLE
[#660] Fix resending invitations and refactor endpoints to not operate on tokens

### LINKED ISSUE #660: Fix resending invitations and refactor endpoints to not operate on tokens
- [ ] Delete old invitation before creating new one
- [ ] Change endpoints to operate on invitations as unique of institution slug and email (UI and Backend)

### PR DESCRIPTION
**Pull request by danielkryska**
**IMPORTANT!!! Includes changes of #643 !!!**

- Delete old invitation before creating new one
- Change endpoints to operate on invitations as unique of institution slug and email (UI and Backend)

Closes #660

### CODE REVIEW

File: s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InvitationController.java [hunk 1]
```diff
@@ -82,27 +82,49 @@ public BasicInvitationResponse send(
...
+                    content = @Content
+            ),
+            @ApiResponse(responseCode = "401", description = "Unauthenticated", content = @Content),
+            @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content),
+            @ApiResponse(responseCode = "404", description = "Not found", content = @Content)
+    })
+    @DeleteMapping(value = "/institutions/{institution}/invitations/{email}")
+    public void delete(
+            @PathVariable("institution") String institutionSlug,
+            @PathVariable String email
```
[the remark this answers is not in the document]
Comment (danielkryska) [reply s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InvitationController.java:118]: I'd be glad to solve this issue like you saying, but as you know `DELETE` doesn't contain body and will required a lot of hacks on UI and backend side...

[the remark this answers is not in the document]
Comment (jswk) [reply s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InvitationController.java:118]: @danielkryska it's actually not true that DELETE doesn't contain request body. See it's specs: https://tools.ietf.org/html/rfc7231#section-4.3.5.

[the remark this answers is not in the document]
Comment (danielkryska) [reply s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InvitationController.java:118]: This issue will be solved by substitution of email with id of invitation

File: s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java [hunk 2]
```diff
@@ -256,25 +241,12 @@ public void shouldReject() throws Exception {
...
-        val newInstitution = institutionRepository
-                .save(InvitationHelper.institutionBuilder().build());
-        val invitation = invitationRepository
-                .save(InvitationHelper.invitationBuilder(newInstitution).build());
-        val URL = API_PREFIX_V1 + "/institutions/{institution}/invitations/{token}";
-        mockMvc.perform(delete(URL, institution.getSlug(), invitation.getToken())
-                .contentType(MediaType.APPLICATION_JSON)
-                .with(jwtBearerToken(institutionAdmin, objectMapper))
-        ).andExpect(status().isBadRequest());
-    }
```
Comment (jswk) [inline s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java:270]: This test shouldn't be removed, the case of privilage escalation in this point could still be possible, you should just test with an id instead of a token.

Comment (danielkryska) [reply s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java:270]: Show me in which of those lines (in controller) and will agree

```
val invitation = invitationService
                .findByIdAndInstitutionSlug(id, institutionSlug, Invitation.class)
                .orElseThrow(() -> new NotFoundException("Invitation couldn't be found"));

        val deleteInvitationEvent = new OnDeleteInvitationEvent(invitation.getToken(), LocaleContextHolder.getLocale());
        eventPublisher.publishEvent(deleteInvitationEvent);

Comment (jswk) [reply s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java:270]: This one could allow for this:
```
@DeleteMapping(value = "/institutions/{institution}/invitations/{id}")
```
The ones you quoted don't have anything to do with that possibility.

Comment (danielkryska) [reply s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java:270]: I can agree only to add a second not found test case when an invitation doesn't exist for certain id. Nothing more nothing less...

Comment (danielkryska) [reply s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java:270]: ok
